add_executable(mig-engine-tests engine_tests.cpp)
target_link_libraries(mig-engine-tests PRIVATE mig-core)
add_test(NAME engine COMMAND mig-engine-tests)
add_executable(mig-realtime-tests realtime_tests.cpp)
target_link_libraries(mig-realtime-tests PRIVATE mig-core)
add_test(NAME realtime COMMAND mig-realtime-tests)
add_executable(mig-constraint-tests constraint_tests.cpp)
target_link_libraries(mig-constraint-tests PRIVATE mig-core)
add_test(NAME constraints COMMAND mig-constraint-tests)
add_executable(mig-session-tests session_tests.cpp)
target_link_libraries(mig-session-tests PRIVATE mig-core)
add_test(NAME session COMMAND mig-session-tests)
add_executable(mig-coordinates-tests coordinates_tests.cpp)
target_link_libraries(mig-coordinates-tests PRIVATE mig-core)
add_test(NAME coordinates COMMAND mig-coordinates-tests)
if(MIG_BUILD_HANDS)
    add_executable(mig-hand-gestures-tests hand_gestures_tests.cpp)
    target_link_libraries(mig-hand-gestures-tests PRIVATE mig-hands)
    add_test(NAME hand-gestures COMMAND mig-hand-gestures-tests)
    add_executable(mig-hands-tests hands_tests.cpp)
    target_link_libraries(mig-hands-tests PRIVATE mig-hands)
    add_test(NAME hands COMMAND mig-hands-tests)
endif()
