if(NOT TARGET MIG::core)
    find_package(MIG 1.0 CONFIG QUIET)
endif()
if(NOT TARGET MIG::core)
    get_filename_component(mig_repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
    if(NOT EXISTS "${mig_repository}/src/core/CMakeLists.txt")
        message(FATAL_ERROR "Install MIG or download the complete repository first.")
    endif()
    set(MIG_BUILD_CONFIGURATOR OFF CACHE BOOL "" FORCE)
    set(MIG_BUILD_CONTROLLER OFF CACHE BOOL "" FORCE)
    set(MIG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(MIG_BUILD_NATIVE_RUNTIME ON CACHE BOOL "" FORCE)
    set(MIG_BUILD_C_API OFF CACHE BOOL "" FORCE)
    set(MIG_INSTALL OFF CACHE BOOL "" FORCE)
    if(WIN32)
        set(mig_dependencies "${mig_repository}/build/native-deps")
    else()
        set(mig_dependencies "${mig_repository}/build/native-linux-deps")
    endif()
    set(MIG_NATIVE_DEPS "${mig_dependencies}" CACHE PATH "Native artifacts")
    add_subdirectory("${mig_repository}" "${CMAKE_BINARY_DIR}/mig-repository")
    foreach(header camera pose runtime)
        configure_file("${mig_repository}/src/native/${header}.hpp"
            "${CMAKE_BINARY_DIR}/repository-include/mig/native/${header}.hpp" COPYONLY)
    endforeach()
    target_include_directories(mig-native INTERFACE "${CMAKE_BINARY_DIR}/repository-include")
endif()

