if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "MIG_PACKAGE_SDK currently generates Linux Debian SDK packages")
endif()
if(MIG_BUILD_CONFIGURATOR OR MIG_BUILD_CONTROLLER OR MIG_BUILD_NATIVE_RUNTIME)
    message(FATAL_ERROR "Debian SDK packaging requires applications and native runtime OFF")
endif()
if(NOT MIG_INSTALL)
    message(FATAL_ERROR "MIG_PACKAGE_SDK requires MIG_INSTALL=ON")
endif()
set(CPACK_GENERATOR DEB)
set(CPACK_PACKAGE_NAME libmig-dev)
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(MIG_PACKAGE_MAINTAINER "Robin-G0 <robin.g0.dev@gmail.com>" CACHE STRING "Debian maintainer name and email")
set(CPACK_PACKAGE_CONTACT "${MIG_PACKAGE_MAINTAINER}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Motion Input Grid C++20 positions SDK and C ABI")
set(CPACK_DEBIAN_PACKAGE_SECTION libdevel)
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/Robin-G0/MIG")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.35), libstdc++6 (>= 11), libgcc-s1")
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE arm64)
else()
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
endif()
install(FILES "${CMAKE_SOURCE_DIR}/LICENSE"
    DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/libmig-dev" RENAME copyright)
if(EXISTS "${MIG_NATIVE_DEPS}/nlohmann-LICENSE")
    install(FILES "${MIG_NATIVE_DEPS}/nlohmann-LICENSE"
        DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/libmig-dev")
endif()
include(CPack)
